#!/bin/python3
#SBATCH -J task1 
#SBATCH -p batch 
#SBATCH -N 1
#SBATCH --ntasks-per-node 24 
#SBATCH --mem 1000 
#SBATCH --time 72:00:00 
#SBATCH --mail-type=END 
#SBATCH --mail-user=ricard.ravellrodriguez@phdstud.ug.edu.pl
module load hi
mpirun hi <hi.py
