#!/bin/bash
#SBATCH -J task1 
#SBATCH -p batch 
#SBATCH -N 5
#SBATCH --ntasks-per-node 24 
#SBATCH --mem 20000 
#SBATCH --time 72:00:00 
#SBATCH --mail-type=END 
#SBATCH --mail-user=ricard.ravellrodriguez@phdstud.ug.edu.pl
module load tryton/python3
python3 <7cells.py
